/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokimons;

import javax.swing.JOptionPane;
import static pokimons.Menu.batalla;
import static pokimons.Menu.jbtMujer;
import static pokimons.Menu.jbtVaron;
import static pokimons.Menu.pok1;
import static pokimons.Menu.pok2;
import static pokimons.Menu.pok3;
import static pokimons.Menu.txtNombre;

/**
 *
 * @author Usuario
 */
public class ElegirNombre extends javax.swing.JFrame {

    /**
     * Creates new form ElegirNombre
     */
    public ElegirNombre() {
        initComponents();
        setLocationRelativeTo(null);//codigo para poner en el medio
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JTextField();
        jlbtexto = new javax.swing.JLabel();
        jbno = new javax.swing.JToggleButton();
        jbsi = new javax.swing.JToggleButton();
        batalla = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoActionPerformed(evt);
            }
        });
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 11, 158, 34));

        jlbtexto.setText("!Desea Cambiar nombre¡");
        getContentPane().add(jlbtexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 17, -1, 22));

        jbno.setText("NO");
        jbno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnoActionPerformed(evt);
            }
        });
        getContentPane().add(jbno, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 63, -1, -1));

        jbsi.setText("SI");
        jbsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsiActionPerformed(evt);
            }
        });
        getContentPane().add(jbsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 63, -1, -1));

        batalla.setText("Iniciar Batalla");
        batalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batallaActionPerformed(evt);
            }
        });
        getContentPane().add(batalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 97, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pokemon texto_opt (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoActionPerformed
        if(jbsi.isSelected()){
            texto.setEditable(true);
            
        }
        else{
            texto.setEditable(false);
            texto.setVisible(false);
        }
    }//GEN-LAST:event_textoActionPerformed

    private void jbnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnoActionPerformed
        if(jbno.isSelected()){
            //jbsi.setEnabled(false);
            texto.setEditable(false);
            
        }
    }//GEN-LAST:event_jbnoActionPerformed

    private void jbsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsiActionPerformed
         if(jbsi.isSelected()){
             texto.setEditable(true);
             
             
         }
        
    }//GEN-LAST:event_jbsiActionPerformed

    private void batallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batallaActionPerformed
        Entrenador1 entrenador = new Entrenador1();
        Entrenador2 entrenador2 =new Entrenador2();
        Entrenador3 entrenador3 = new Entrenador3();
        Entrenador4 entrenador4 = new Entrenador4();
        Entrenador5 entrenador5 = new Entrenador5();
        Entrenador6 entrenador6 = new Entrenador6();
        
       
        
        entrenador.jlb1.setText(txtNombre.getText());
        entrenador3.jlb2.setText(txtNombre.getText());
        entrenador2.jlb3.setText(txtNombre.getText());
        entrenador4.jlb4.setText(txtNombre.getText());
        entrenador5.jlb5.setText(txtNombre.getText());
        entrenador6.jlb6.setText(txtNombre.getText());
        
        
        //entrenador.txtVaron.setText(txtNombre.getText());
       //String mostrar="";
       //String a =(JOptionPane.showInputDialog(this,"Desea poner un nombre al pokemon"));
       
       
        
       if(jbtMujer.isSelected() && pok1.isSelected()){
           entrenador.setVisible(true);
           this.dispose();
          
            //entrenador.txt1.setText(a);   //obtiene el texto que se inserta en a            
            
            
        }else if(jbtMujer.isSelected() && pok2.isSelected()){   
            entrenador3.setVisible(true);
            this.dispose();
            //entrenador3.txt2.setText(a);
            
            
            
        }else if (jbtMujer.isSelected() && pok3.isSelected()){
            entrenador2.setVisible(true);
            this.dispose();
            //entrenador2.txt2.setText(a);
            
            
            
        }else if (jbtVaron.isSelected() && pok1.isSelected()){
            entrenador4.setVisible(true);
            this.dispose();
            //entrenador4.txt2.setText(a);
            
            
            
        }else if (jbtVaron.isSelected() && pok2.isSelected()){
            entrenador5.setVisible(true);
            this.dispose();
            //entrenador6.txt2.setText(a);
            
            
            
        }else if(jbtVaron.isSelected() && pok3.isSelected()){
            entrenador6.setVisible(true);
            this.dispose();
            //entrenador5.txt2.setText(a);*/
            
        }
    }//GEN-LAST:event_batallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirNombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton batalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jbno;
    private javax.swing.JToggleButton jbsi;
    private javax.swing.JLabel jlbtexto;
    public static javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables

    private Menu Menu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

      


}
