/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokimons;

import Atxy2k.CustomTextField.RestrictedTextField;
import javax.swing.JOptionPane;
import static pokimons.Menu.batalla;
import static pokimons.Menu.jbtMujer;
import static pokimons.Menu.jbtVaron;
import static pokimons.Menu.pok1;
import static pokimons.Menu.pok2;
import static pokimons.Menu.pok3;
import static pokimons.Menu.txtNombre;

/**
 *
 * @author Usuario
 */
public class ElegirNombre extends javax.swing.JFrame {

    /**
     * Creates new form ElegirNombre
     */
    public ElegirNombre() {
        initComponents();
        setLocationRelativeTo(null);//codigo para poner en el medio
        setResizable(false);
        RestrictedTextField a = new RestrictedTextField(nombre);
        a.setLimit(10);
        a.setOnlyAlphaNumeric(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        jlbtexto = new javax.swing.JLabel();
        no = new javax.swing.JToggleButton();
        si = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 11, 158, 34));

        jlbtexto.setText("!Desea Cambiar nombre¡");
        getContentPane().add(jlbtexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 17, -1, 22));

        no.setText("PorDefecto");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, -1));

        si.setText("Cambiar");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });
        getContentPane().add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 80, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pokemon texto_opt (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 130));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 140, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        if(si.isSelected()){
            nombre.setEditable(true);
            
        }
        else{
            nombre.setEditable(false);
            nombre.setVisible(false);
        }
    }//GEN-LAST:event_nombreActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        Entrenador1 entrenador = new Entrenador1();
        Entrenador2 entrenador2 =new Entrenador2();
        Entrenador3 entrenador3 = new Entrenador3();
        Entrenador4 entrenador4 = new Entrenador4();
        Entrenador5 entrenador5 = new Entrenador5();
        Entrenador6 entrenador6 = new Entrenador6();
        
        entrenador.jlb1.setText(txtNombre.getText());
        entrenador3.jlb2.setText(txtNombre.getText());
        entrenador2.jlb3.setText(txtNombre.getText());
        entrenador4.jlb4.setText(txtNombre.getText());
        entrenador5.jlb5.setText(txtNombre.getText());
        entrenador6.jlb6.setText(txtNombre.getText());
        
        if(jbtMujer.isSelected() && pok1.isSelected() && !txtNombre.getText().isEmpty()){
            entrenador.txt1.setText("Groudon");
            entrenador.setVisible(true);
            //entrenador.txt1.setText(a);   //obtiene el texto que se inserta en a            
            
            dispose();
            
        }else if(jbtMujer.isSelected() && pok2.isSelected()&& ! txtNombre.getText().isEmpty()){           
            //entrenador3.txt2.setText(a);
            entrenador3.txt2.setText("Sceptile");
            entrenador3.setVisible(true);
            dispose();
            
        }else if (jbtMujer.isSelected() && pok3.isSelected()&& !txtNombre.getText().isEmpty()){
            //entrenador2.txt2.setText(a);
            entrenador2.txt2.setText("Suicune");
            entrenador2.setVisible(true);
            dispose();
            
        }else if (jbtVaron.isSelected() && pok1.isSelected()&& !txtNombre.getText().isEmpty()){
            //entrenador4.txt2.setText(a);
            entrenador4.txt2.setText("Groudon");
            entrenador4.setVisible(true);
            dispose();
            
        }else if (jbtVaron.isSelected() && pok2.isSelected()&& !txtNombre.getText().isEmpty()){
            //entrenador6.txt2.setText(a);
            entrenador6.txt2.setText("Sceptile");
            entrenador6.setVisible(true);
            dispose();
            
            
        }else if(jbtVaron.isSelected() && pok3.isSelected()&& !txtNombre.getText().isEmpty()){
            //entrenador5.txt2.setText(a);*/
            entrenador5.txt2.setText("Suicune");
            entrenador5.setVisible(true);
            dispose();
        
       
        }
          
          
            
        
    }//GEN-LAST:event_noActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        Entrenador1 entrenador = new Entrenador1();
        Entrenador2 entrenador2 =new Entrenador2();
        Entrenador3 entrenador3 = new Entrenador3();
        Entrenador4 entrenador4 = new Entrenador4();
        Entrenador5 entrenador5 = new Entrenador5();
        Entrenador6 entrenador6 = new Entrenador6();
        
        entrenador.jlb1.setText(txtNombre.getText());
        entrenador3.jlb2.setText(txtNombre.getText());
        entrenador2.jlb3.setText(txtNombre.getText());
        entrenador4.jlb4.setText(txtNombre.getText());
        entrenador5.jlb5.setText(txtNombre.getText());
        entrenador6.jlb6.setText(txtNombre.getText());
        
        if(jbtMujer.isSelected() && pok1.isSelected() && !nombre.getText().isEmpty()){
            entrenador.txt1.setText(nombre.getText());
            entrenador.setVisible(true);
            dispose();
        }  //entrenador.txt1.setText(a);   //obtiene el texto que se inserta en a            
        else{
                jLabel2.setText("complete el campo ");
             }    
            
            
         if(jbtMujer.isSelected() && pok2.isSelected()&& !nombre.getText().isEmpty()){           
            //entrenador3.txt2.setText(a);
            entrenador3.txt2.setText(nombre.getText());
            entrenador3.setVisible(true);
            dispose();
         }
         else{
                jLabel2.setText("complete el campo ");
             }    
            
         if (jbtMujer.isSelected() && pok3.isSelected()&& !nombre.getText().isEmpty()){
            //entrenador2.txt2.setText(a);
            entrenador2.txt2.setText(nombre.getText());
            entrenador2.setVisible(true);
            dispose();
            
        }
         else{
                jLabel2.setText("complete el campo ");
             }    
         if (jbtVaron.isSelected() && pok1.isSelected()&& !nombre.getText().isEmpty()){
            //entrenador4.txt2.setText(a);
            entrenador4.txt2.setText(nombre.getText());
            entrenador4.setVisible(true);
            dispose();
            
        }else{
                jLabel2.setText("complete el campo ");
             }    
         
         if (jbtVaron.isSelected() && pok2.isSelected()&& !nombre.getText().isEmpty()){
            //entrenador6.txt2.setText(a);
            entrenador6.txt2.setText(nombre.getText());
            entrenador6.setVisible(true);
            dispose();
            
            
        }else{
                jLabel2.setText("complete el campo ");
             }    
         
         if(jbtVaron.isSelected() && pok3.isSelected()&& !nombre.getText().isEmpty()){
            //entrenador5.txt2.setText(a);*/
           entrenador5.txt2.setText(nombre.getText());
           entrenador5.setVisible(true);
            dispose();
         }
         else{
                jLabel2.setText("complete el campo ");
             }    
       
         
        
    }//GEN-LAST:event_siActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirNombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbtexto;
    private javax.swing.JToggleButton no;
    public static javax.swing.JTextField nombre;
    private javax.swing.JToggleButton si;
    // End of variables declaration//GEN-END:variables

    private Menu Menu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

      


}
